# Generated by Django 5.1.4 on 2025-01-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='email',
        ),
    ]
