# Generated by Django 5.1.4 on 2025-01-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0002_rename_user_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='user',
        ),
    ]
