# Generated by Django 5.1.4 on 2025-01-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pasword', models.CharField(max_length=100)),
            ],
        ),
    ]
