# Generated by Django 5.1.4 on 2025-01-18 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0005_logininfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logininfo',
            old_name='pasword',
            new_name='password',
        ),
        migrations.AddField(
            model_name='logininfo',
            name='logged_in_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
