# Generated by Django 5.1.4 on 2025-01-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0006_rename_pasword_logininfo_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='logininfo',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254),
        ),
    ]
