# Generated by Django 5.1.4 on 2025-01-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0007_rename_name_user_first_name_logininfo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logininfo',
            name='logged_in_at',
        ),
        migrations.RemoveField(
            model_name='logininfo',
            name='username',
        ),
    ]
