# Generated by Django 5.1.4 on 2025-01-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0009_rename_email_logininfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logininfo',
            old_name='user',
            new_name='username',
        ),
    ]
