# Generated by Django 5.1.4 on 2025-01-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0010_rename_user_logininfo_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
